version: '3.5'

services:

  flask:
    container_name: flask_dash
    build: ./flask_dash
    tty: true
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask
