version: '3.5'

services:

  dash:
    container_name: dash
    build: ./dash
    tty: true
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash
